Add SetupWizard libs from AOSP
stevesoltys/backup pull request #392
Opened 2022-03-24 09:38 UTC by chirayudesai

2022-03-24 09:39 UTC, chirayudesai commented
It doesn't compile due to https://github.com/seedvault-app/setupcompat/blob/13644ae60092b3469c81dad57d58520916f7cb60/build.gradle#L19

Adding it there worked however. Also, setupdesign has it set to 28.

@grote what's the best way to deal with this?

2022-03-24 09:42 UTC, chirayudesai commented
Other build issues:

Caused by: java.lang.RuntimeException: Error while processing seedvault/setupdesign/main/res/drawable-anydpi-v21/sud_navbar_ic_next.xml Width (0) and height (0) cannot be <= 0

It has width and height set to `@dimen/sud_navbar_ic_intrinsic_size`, which is defined in setupdesign/main/res/values/dimens.xml

2022-03-24 10:20 UTC, chirayudesai commented
Builds with:

* https://github.com/seedvault-app/setupcompat/pull/1
* https://github.com/seedvault-app/setupdesign/pull/1

2022-03-28 15:30 UTC, grote requested changes
I stopped half way through reviewing this, because I kept coming across the same issues. Also, since layout previews don't work, could I please get before and after screenshots?

To be honest, I am also a bit skeptical pulling in these two libraries as submodules is worth it for the relatively minor UI changes they bring while at the same time losing tooling support for the parts they do bring.

2022-03-28 15:30 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/restore/RestoreFilesFragment.kt
> +        val icon: Drawable = suwLayout.getIcon()
If you open this in Android Studio, it tells you to use kotlin syntax instead: `suwLayout.icon`.
 Same below in this file.

2022-03-28 15:30 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/restore/RestoreFilesFragment.kt
> +        suwLayout.setIcon(icon)
If you open this in Android Studio, it tells you to use kotlin syntax instead: `suwLayout.icon = icon`.
Same below in this file.

2022-03-28 15:30 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/restore/RestoreFilesFragment.kt
> +        icon.setTintList(getColorAccent(requireContext()))
Can't the `GlifLayout` handle icon tinting in a better way? Do we have to do these acrobatics here just to apply a tint? As this code change happens a lot, maybe worth looking into this? There's a `sudIconTint` attribute for example and a special theme. Also a `IconMixin` with a `setIconTint()` method which might help.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_progress.xml
> +            android:layout_marginTop="16dp"
The progress was neatly anchored at the top before, now there's this empty space above. Is this intentional?

2022-03-28 15:30 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/ui/UiUtils.kt
> +fun getColorAccent(context: Context): ColorStateList? {
Is this maybe available in the libs we are including as submodule now?

2022-03-28 15:30 UTC, grote commented on app/src/main/java/com/stevesoltys/seedvault/ui/UiUtils.kt
> +    var stateList: ColorStateList? = null
`= null` is redundant and can be removed. Could the `var` also be a `val`?

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_files_started.xml
> +            app:layout_constraintTop_toBottomOf="@+id/titleView"
There is no more `titleView` in this layout. You would need to use something like `app:layout_constraintTop_toTopOf="parent"` now.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_files_started.xml
>      xmlns:tools="http://schemas.android.com/tools"
Looks like this isn't used anymore in the XMl file.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_progress.xml
> +    android:icon="@drawable/ic_cloud_download"
Unfortunately, the layout preview in Android Studio isn't working for that `GlifLayout`, so I can't see how this looks in practice.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_set.xml
> +            app:layout_constraintTop_toBottomOf="@+id/imageView"
`imageView` doesn't exist anymore in this layout, the constraint would need to be adapted.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_set.xml
> -        android:layout_margin="16dp"
The margin is gone in the new version. Is this intentional?

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_set.xml
> -        app:layout_constraintBottom_toTopOf="@+id/skipView"
This bottom constraint got removed. Intentionally? I am skeptical that `android:layout_height="0dp"` will work like this.

Also, now the list is most likely overlaying (or underlaying) the skip view.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_set.xml
> -        app:layout_constraintBottom_toTopOf="@+id/skipView"
This is missing in the new layout most likely causing the view to jump to the top instead of being vertically centered.

2022-03-28 15:30 UTC, grote commented on app/src/main/res/layout/fragment_restore_set.xml
> -        app:layout_constraintBottom_toTopOf="@+id/skipView"
This is missing in the new layout most likely causing the view to jump to the top instead of being vertically centered.

2022-03-28 19:26 UTC, chirayudesai commented on app/src/main/java/com/stevesoltys/seedvault/ui/UiUtils.kt
> +fun getColorAccent(context: Context): ColorStateList? {
No, SettingsLib is it's own behemoth and not something that's easy to include (nor should we)

2022-03-28 19:33 UTC, chirayudesai commented
> I stopped half way through reviewing this, because I kept coming across the same issues. Also, since layout previews don't work, could I please get before and after screenshots?
> 

Will do. For testing I've been `adb installing` this new APK, and then `*#*#RESTORE#*#*`

> To be honest, I am also a bit skeptical pulling in these two libraries as submodules is worth it for the relatively minor UI changes they bring while at the same time losing tooling support for the parts they do bring.

We can re-consider your previous idea of just doing the same layout ourselves directly without these libs, and we can always copy paste certain stuff as needed (dimens / colors / etc)

2022-04-06 22:25 UTC, chirayudesai commented
Before:
![Screenshot_20220407-033734](https://user-images.githubusercontent.com/952062/162082309-5710c413-02ed-4d19-ae58-f3d10cae1713.png)

After:
![Screenshot_20220407-020737_Seedvault](https://user-images.githubusercontent.com/952062/162082305-8c37d3d4-ae4d-457b-8182-2647481230d4.png)


The after is how the rest of the SetupWizard will look going forward (it's close to what Google's looks like), and thus Seedvault restore UI should match that.

2022-04-29 18:29 UTC, chirayudesai commented
Closing this, we should implement the UI directly without the setuplibs to

1. Keep the layouts functional in Android Studio
2. Avoid additional dependencies.

It just has to look the same to make it seamless with the SetupWizard, doesn't need to use the same libs.

The lib and Seedvault are both Apache2 so we can freely copy paste things as needed.

2022-04-29 18:29 UTC, closed without merging