Updates for Android 14 QPR1
stevesoltys/backup pull request #630
Opened 2024-03-06 15:24 UTC by grote

2024-03-06 15:29 UTC, chirayudesai commented on build.plugins.toml
> +# 1.9.0 Android 14 (QPR1)
QPR2

2024-03-06 15:30 UTC, chirayudesai commented
Let's see what the CI tests say. Also worth doing a quick smoke test on device.

2024-03-06 16:53 UTC, theimpulson commented on build.plugins.toml
> +# 1.9.0 Android 14 (QPR1)
Done

2024-03-07 00:00 UTC, chirayudesai commented
Builds fine in AOSP locally.

2024-03-07 07:42 UTC, theimpulson commented
Seems to build and work fine for me

2024-03-07 14:04 UTC, chirayudesai requested changes
Crashes with biometrics enabled https://zifb.in/raw/VSPqq9RC9F

2024-03-07 15:09 UTC, chirayudesai approved these changes

2024-03-07 15:09 UTC, chirayudesai commented
> Crashes with biometrics enabled https://zifb.in/raw/VSPqq9RC9F

Seems to have solved itself afte reflash, likely a bad state temporarily.

2024-03-07 15:10 UTC, merged