Ask on first run if user wants restore
stevesoltys/backup pull request #717
Opened 2024-08-15 16:29 UTC by grote

Part of #671

Fixes #571

2024-08-15 20:36 UTC, t-m-w requested changes
This new screen ignores the Back button, regardless of whether it's launched via Settings or via a launcher icon. Can that be fixed?

2024-08-15 21:02 UTC, grote commented
thanks. fixed back navigation.

2024-08-15 21:16 UTC, t-m-w approved these changes, later dismissed
Thanks, works!

2024-08-16 08:22 UTC, theimpulson approved these changes
LGTM

2024-08-21 14:40 UTC, t-m-w approved these changes
Still works as expected for me.

2024-08-21 17:24 UTC, merged