Bump version to 15-5.1
stevesoltys/backup pull request #801
Opened 2024-11-20 19:12 UTC by lucasmz-dev

CC @grote

2024-11-20 21:03 UTC, chirayudesai requested changes
Nit inline.

These are meant to be user-facing changelogs, we don't necessarily have to mention all commits

2024-11-20 21:03 UTC, chirayudesai commented on CHANGELOG.md
> +* SeedVault no longer shows up in backup status
I think we can exclude this, it confused me to see this mentioned before I found the commit and figured out what it means.

2024-11-20 21:03 UTC, chirayudesai commented on CHANGELOG.md
> +* The entire WebDAV URL is now shown when on settings
```suggestion
* The entire WebDAV URL is now shown when in settings
```

2024-11-20 21:03 UTC, chirayudesai commented on CHANGELOG.md
> +* A launch button is now shown to apps that are force-stopped so they can be backed up
```suggestion
* A launch button is now shown for apps that are force-stopped so that they can be backed up
```

2024-11-20 21:03 UTC, chirayudesai commented on CHANGELOG.md
> +* It is now possible to verify the integrity of app backups, partially or fully
I'd make this the first thing mentioned, it's pretty big!

2024-11-20 21:22 UTC, lucasmz-dev commented
@chirayudesai applied changes

2024-11-20 21:25 UTC, chirayudesai approved these changes

2024-11-21 12:49 UTC, grote commented
Thanks @lucasmz-dev

2024-11-21 12:49 UTC, merged